### ISSUE TITLE
Guild Blog getting hung up after editing again once posted

### ISSUE THREAD

**Issue by pstan26** [jay-ithiel/guild#17]
![screen shot 2017-08-10 at 12 02 59 pm](https://user-images.githubusercontent.com/5605552/29180037-6fb52cba-7dc4-11e7-8370-a11e64cae517.png)
![screen shot 2017-08-10 at 12 03 55 pm](https://user-images.githubusercontent.com/5605552/29180038-6fbdb416-7dc4-11e7-969f-51c2a420df8a.png)

Still loading and hasn't updated. Otherwise blog is looking pretty good!

**Comment by dgsus** [comment]
working fine on my browser, hang'ed for about 3 seconds and posted my edit

**Comment by jay-ithiel** [comment]
Tried to replicate issue. Edited multiple times and it is working fine on my end as well.
Can you create a new blog and try editing again and see if the issue persists?

**Comment by jay-ithiel** [comment]
Ran into this same issue during development. Fixed the issue. Closing. Reopen if the issue persists
