### ISSUE TITLE
feature request: do some UX mocking up of the blog post composer to give an experience that's more intuitive and more comparable to that of Medium

### ISSUE THREAD

**Issue by shea256** [jay-ithiel/guild#18]

**Comment by jay-ithiel** [comment]
Agreed. Would love some UI/UX help on the entire site. Will use Medium as a guide for the time being.

**Comment by jay-ithiel** [comment]
Latest release enhanced the text-editor that's more comparable to Medium's blog post composing experience. Try it out and let me know what you think! Closing this for now, but feel free to re-open
