### ISSUE TITLE
suggestion: replace cloudinary with a simple photo uploader

### ISSUE THREAD

**Issue by shea256** [jay-ithiel/guild#20]
First, it'll remove external dependencies which can actually be a bigger deal than you might think.

Two, I've found that anything beyond simple file uploaders is unnecessary. I've been tempted to use more advanced systems before but in practice they're worse.

The external plugin also detracts from the design and dilutes the brand.

Last, consider that medium uses a simple file uploader. My view is that in this case if it's good for them then it should be good for Guild.

**Comment by jay-ithiel** [comment]
Replaced
