### ISSUE TITLE
After creating blog post, app breaks

### ISSUE THREAD

**Issue by dhealy05** [jay-ithiel/guild#28]
I logged on with BlockStack, wrote up a post, and tried to publish. Since then, when I open the app, it seems to be broken, not sure if my post was saved, etc. 

Console shows the following:

VM59 main.0a8248dc.js:1 Error during service worker registration: DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).

localhost:6270/v1/stores/14bnMVJxQNfcotsmiU8ERhfD4A9w7B2uj8/files?path=/users.json&idata=1&device_ids=0&device_pubkeys=035a28a81db47567a0ee8aa1407f7bfb1c6c72e240e92e2960abb6fa21efe99a55&blockchain_id=b75da3ce8e5b6aa1b2a7eb9c19cae0d314f26222d058fdc9dd6eb7df1157a358 
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by joshuadanpeterson** [comment]
This happens to me, too. I don't get an error code, the post just disappears after I hit publish.

**Comment by jay-ithiel** [comment]
Guild had some issues these past few weeks. Everything should be working again now. Please feel free to raise more issues for any problems/bugs you encounter!

**Comment by joshuadanpeterson** [comment]
Cool - I'll check it out today and report back. Thanks!
